# Generated by Django 4.1.7 on 2023-04-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departmen',
            new_name='Department',
        ),
    ]
