# Generated by Django 4.1.7 on 2023-04-05 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst_app', '0002_rename_departmen_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
